### ISSUE TITLE
РК2 стр. 3 неправильно отображается дробь, не тот коэффициент

### ISSUE THREAD

**Issue by NovaIscariot** [Euclidophren/mathstat#8]
Ошибка в выводе критерия Неймана-Пирса. В самом низу перед словами "с учетом".
1) У суммы стоит коэф m1^2-m0^2 вместо m1-m0
2) В слагаемом справа коэф m1^2-m0^2 оказалсяв знаменателе
До этого места и после него все верно, то есть вывод сам верный, расхождения только на этой стадии

**Comment by Euclidophren** [comment]
Исправлено. 69c5b95d9bb6e2f0d2a9c90d34b5353288a0afe6
